android.useAndroidX=true
android.nonTransitiveRClass=true
android.bundle.enableUncompressedNativeLibs=false
android.packagingOptions.jniLibs.useLegacyPackaging=false
ndkVersion=27.2.12479018
org.gradle.jvmargs=-Xmx8192m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
